CREATE TABLE IF NOT EXISTS public.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(150) NOT NULL,
    password_hash varchar(255) NOT NULL,
    full_name varchar(200) NOT NULL,
    role varchar(32) NOT NULL
        CHECK (role IN ('STATE_ADMIN', 'DISTRICT_OFFICER', 'BLOCK_OFFICER')),
    district varchar(100),
    block varchar(100),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_role_scope_valid CHECK (
        (role = 'STATE_ADMIN' AND district IS NULL AND block IS NULL)
        OR (role = 'DISTRICT_OFFICER' AND district IS NOT NULL)
        OR (role = 'BLOCK_OFFICER' AND district IS NOT NULL AND block IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username ON public.users (username);
CREATE INDEX IF NOT EXISTS users_role_idx ON public.users (role);
CREATE INDEX IF NOT EXISTS users_district_idx ON public.users (district);
CREATE INDEX IF NOT EXISTS users_block_idx ON public.users (block);
