CREATE TABLE IF NOT EXISTS public.data_uploads (
    id uuid PRIMARY KEY,
    created_by integer NOT NULL
        REFERENCES public.users(id) ON DELETE RESTRICT,
    scope_district varchar(100),
    scope_block varchar(100),
    dataset_type varchar(32) NOT NULL DEFAULT 'GOVERNMENT_UPLOAD'
        CHECK (dataset_type = 'GOVERNMENT_UPLOAD'),
    filename varchar(255) NOT NULL,
    file_type varchar(8) NOT NULL
        CHECK (file_type IN ('CSV', 'XLSX', 'PDF')),
    status varchar(16) NOT NULL
        CHECK (status IN ('COMPLETED', 'PARTIAL', 'FAILED')),
    row_count integer NOT NULL CHECK (row_count >= 0),
    valid_rows integer NOT NULL CHECK (valid_rows >= 0),
    rejected_rows integer NOT NULL CHECK (rejected_rows >= 0),
    detected_columns jsonb NOT NULL,
    mapped_columns jsonb NOT NULL,
    unmapped_columns jsonb NOT NULL,
    validation_errors jsonb NOT NULL,
    warnings jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT data_uploads_row_counts_valid
        CHECK (valid_rows + rejected_rows = row_count),
    CONSTRAINT data_uploads_scope_valid
        CHECK (scope_block IS NULL OR scope_district IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS data_uploads_scope_idx
    ON public.data_uploads (scope_district, scope_block);
CREATE INDEX IF NOT EXISTS data_uploads_created_at_idx
    ON public.data_uploads (created_at);

CREATE TABLE IF NOT EXISTS public.imported_data_rows (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id uuid NOT NULL
        REFERENCES public.data_uploads(id) ON DELETE CASCADE,
    row_number integer NOT NULL CHECK (row_number > 0),
    district varchar(100) NOT NULL,
    block varchar(100),
    normalized_data jsonb NOT NULL,
    CONSTRAINT imported_data_rows_upload_row_unique
        UNIQUE (upload_id, row_number)
);

CREATE INDEX IF NOT EXISTS imported_data_rows_scope_idx
    ON public.imported_data_rows (district, block);
